# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
