# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20160908_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='user',
            new_name='users',
        ),
    ]
